host: 0.0.0.0

sass:
    style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "NS Zakelijk"
  - scope:
      path: "mijnnszakelijk"
      type: pages
    values:
      layout: "default"
      title: "Mijn NS Zakelijk"
      no-footer: true